import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import {notFound} from 'next/navigation';

const locales = ['en', 'de', 'es', 'jp'];

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '.moai.',
  description: 'Generated by us',
}

export default function RootLayout({children, params: {locale}}: {children: React.ReactNode, params: any}) {
  if (!locales.includes(locale as any)) notFound();
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}